apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/ashish01987/mymicro/helloworld-service:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ghcr-secret-1

