apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
      - name: ui-service
        image: ghcr.io/ashish01987/mymicro/ui-service:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-secret-1
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort  # Change to LoadBalancer if you're in the cloud

