name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Adjust this if you're using a different  branch

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT }}"  | docker login ghcr.io -u "${{ github.actor }}" --password-stdin


      # Step 3: Build Docker image for HelloWorld Service
      - name: Build HelloWorld Service Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/helloworld-service:latest -f docker/Dockerfile .

      # Step 4: Push HelloWorld Service Docker image to GitHub Packages
      - name: Push HelloWorld Service Docker image
        run: docker push ghcr.io/${{ github.repository }}/helloworld-service:latest

      # Step 5: Build Docker image for DB Service
      - name: Build DB Service Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/db-service:latest -f dbservice/docker/Dockerfile .

      # Step 6: Push DB Service Docker image to GitHub Packages
      - name: Push DB Service Docker image
        run: docker push ghcr.io/${{ github.repository }}/db-service:latest

